apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
  - host: foo2.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
  tls:
  - secretName: nginx-test-cert
    hosts:
      - foo.bar
      - foo2.bar
#openssl req -x509 \
#  -newkey rsa:2048 \
#  -keyout api.test.local.key \
#  -out api.test.local.crt \
#  -days 365 \
#  -nodes \
#  -subj "/C=US/ST=Ohio/L=Columbus/O=MyCompany/CN=api.test.com"
#kubectl create secret tls nginx-test-cert \
#  --key="api.test.local.key" \
#  --cert="api.test.local.crt"
