apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: nginx-http
    - port: 443
      name: nginx-https
    - port: 22
      name: ssh
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: pod-service-access
      containers:
      - image: nginx-alpine:v1
        imagePullPolicy: Never
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 20
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /data
        - name: varlog
          mountPath: /var/log
        - name: certificate
          mountPath: /cert
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-pv-claim
      - name: certificate
        secret:
          secretName: nginx-cert
      - name: varlog
        emptyDir: {}
