apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
    - name: mysql
      port: 3306
      protocol: TCP
  selector:
    app: mariadb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      serviceAccount: pod-service-access
      containers:
      - image: mariadb-alpine:v1
        imagePullPolicy: Never
        name: mariadb
        ports:
        - containerPort: 3306
          hostPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 180
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 180
          periodSeconds: 20
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        - name: mariadb-secrets
          readOnly: true
          mountPath: /auth
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: mariadb-secrets
        secret:
          secretName: mariadb-secrets
      - name: varlog
        emptyDir: {}
