apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - name: phpmyadmin
      port: 5000
      protocol: TCP
    - name: ssh
      port: 22
      protocol: TCP
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.141
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      serviceAccount: pod-service-access
      containers:
      - image: phpmyadmin-alpine:v1
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
          hostPort: 5000
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 20
        volumeMounts:
        - name: phpmyadmin-persistent-storage
          mountPath: /data
        - name: php-config
          readOnly: true
          mountPath: /config
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim
      - name: php-config
        secret:
          secretName: phpmyadmin-config
      - name: varlog
        emptyDir: {}
