apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: vsftpd-cert-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vsftpd-cert
  namespace: default
spec:
  secretName: vsftpd
  commonName: vsftpd
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  dnsNames:
    - vsftpd
  secretName: vsftpd-cert
  issuerRef:
    name: vsftpd-cert-issuer
