apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  labels:
    app: phpfpm
spec:
  ports:
    - name: phpfpm
      port: 9000
      protocol: TCP
    - name: ssh
      port: 22
      protocol: TCP
  selector:
    run: phpfpm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpfpm-pv-claim
  labels:
    app: phpfpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: phpfpm
spec:
  selector:
    matchLabels:
      app: phpfpm
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      serviceAccount: pod-service-access
      containers:
      - image: phpfpm-alpine:v1
        imagePullPolicy: Never
        name: phpfpm
        ports:
        - containerPort: 9000
          hostPort: 9000
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: phpfpm-persistent-storage
          mountPath: /data
        - name: php-config
          readOnly: true
          mountPath: /config
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: phpfpm-persistent-storage
        persistentVolumeClaim:
          claimName: phpfpm-pv-claim
      - name: php-config
        secret:
          secretName: php-config
      - name: varlog
        emptyDir: {}
