apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  labels:
    app: phpfpm
spec:
  ports:
    - port: 80
      name: phpfpm-http
    - port: 443
      name: phpfpm-https
    - port: 22
      name: ssh
  selector:
    app: phpfpm
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpfpm-pv-claim
  labels:
    app: phpfpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: phpfpm
spec:
  selector:
    matchLabels:
      app: phpfpm
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      serviceAccount: pod-service-access
      containers:
      - image: phpfpm-alpine:v1
        imagePullPolicy: Never
        name: phpfpm
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: phpfpm-persistent-storage
          mountPath: /data
        - name: varlog
          mountPath: /var/log
        - name: certificate
          mountPath: /cert
      volumes:
      - name: phpfpm-persistent-storage
        persistentVolumeClaim:
          claimName: phpfpm-pv-claim
      - name: certificate
        secret:
          secretName: phpfpm-cert
      - name: varlog
        emptyDir: {}
