apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: nginx.kub
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
